import os

class Metric:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int | float: ...
    @property
    def unit(self) -> str: ...

class SourceMetrics:
    @property
    def name(self) -> str: ...
    @property
    def metrics(self) -> tuple[Metric, ...]: ...

class Phase:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def start_token(self) -> str: ...
    @property
    def end_token(self) -> str: ...
    @property
    def start_line(self) -> int | None: ...
    @property
    def end_line(self) -> int | None: ...
    @property
    def timestamp_us(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def sources(self) -> tuple[SourceMetrics, ...]: ...

class Summary:
    @property
    def timestamp_us(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def phases(self) -> int: ...
    @property
    def exit_code(self) -> int | None: ...

class Run:
    def __iter__(self) -> Run: ...
    def __next__(self) -> Phase: ...
    def poll(self) -> Phase | None: ...
    @property
    def summary(self) -> Summary: ...

class _Session:
    @property
    def run(self) -> Run: ...
    def phase(self, name: str) -> None: ...
    def finish(self, exit_code: int) -> None: ...

class _Profiler:
    def __init__(
        self,
        sources: list[str],
        config: str | os.PathLike[str] | None,
        values: str,
    ) -> None: ...
    def list_sensors(self) -> str: ...
    def info(self) -> str: ...
    def profile(
        self,
        command: list[str],
        token_pattern: str | None = None,
        stdout_file: str | os.PathLike[str] | None = None,
        use_root: bool | None = None,
    ) -> Run: ...
    def session(self, command: list[str]) -> _Session: ...

def _serve() -> None: ...
